### PR TITLE
Added null geometry type

### PR DESCRIPTION
**Pull request by flippmoke**
Added a null type geometry - related to original discussion on #28. 

It is a contentious topic in some ways, but I think that we should consider using a null geometry type again. The biggest reason I keep running into using this is frankly that it is very difficult to try to use a geometry object that is not wrapped in a pointer (through an optional) and it is very difficult to initialize an empty geometry prior to having your data prepared.

Additionally, I think it might be useful to have as a geometry type in general. In the OGC simple feature spec, there is the concept of an `empty set` which could mean a null geometry in the case of a point geometry. Otherwise we have no way to represent this currently.

/cc @artemp

### CODE REVIEW

**Comment by jfirebaugh** [comment]
As [before](https://github.com/mapbox/geometry.hpp/issues/44), I'm opposed to doing this. Making geometry effectively nullable weakens the invariants of the type, meaning that all code that uses it must either explicitly guard against null, define what its behavior is in that case (and often there's no clear correct behavior), or risk behaving unexpectedly in the face of an input that was assumed not to be null. It's trouble-making for the same reason that nullable-by-default pointers are the ["billion dollar mistake"](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions).

**Comment by joto** [comment]
As @flippmoke mentioned having a null geometry is often useful in code. I see the problems @jfirebaugh mentions as less of a problem in this case, because geometries always have a type and basically every piece of code has to switch on this type anyway. There is different code for points, linestrings, polygons, whatever. One more option isn't a big deal. C++ compilers will warn you if you don't  cover all types in the switch. This is very different from the nullable pointer where the typical operation is accessing data through the pointer where the check is an extra operation you might miss.

**Comment by flippmoke** [comment]
@artemp I really like these changes very nice!

**Comment by jfirebaugh** [comment]
@joto Null geometries are never wanted in Mapbox GL. I don't want the types Mapbox GL uses to allow the possibility of null geometries; that would introduce non-trivial complexity and possibility of bugs. If this change is merged, we will need to fork geometry.hpp for use in Mapbox GL.

**Comment by jfirebaugh** [comment]
As an example of the accidental complexity null geometries introduce -- this changes the possible results of the `envelope` function. It can now return an invalid `box<T>` (min > max), and all downstream code will need to be prepared for that possibility.

**Comment by flippmoke** [comment]
@jfirebaugh wouldn't an `isEmpty()` method work for preventing  empty/null geometries? Do you not already have to deal with this logic in some ways for invalid points and other problems?

**Comment by jfirebaugh** [comment]
That would be a runtime check. It can a) be easily forgotten and b) is an extra code branch that you have to figure out how to handle -- e.g. what do you return in that case? Null geometries force you to have to remember to make the check, and force you to make a decision about what to do if it fails, _everywhere_. That's accidental complexity that permeates your whole program. Using `optional<geometry>` only where you _actually_ want and need the possibility of a null is more flexible and less complex overall. It may appear more complex in localized areas, but I submit that that's not actually complexity caused by `optional<geometry>` _itself_, but `optional<geometry>` _forcing_ you to deal with the inherent complexity that a nullable type introduces. When you build that inherent complexity into the base type, that complexity can't be localized -- it's everywhere in your program, waiting to produce bugs because you forgot to add an `isEmpty()` check, or because you forgot to account for the possibility that a geometry algorithm encountered a null geometry and returned an unexpected result, like in the `envelope` example.

**Comment by flippmoke** [comment]
@jfirebaugh on the algorithms end a lack of null can introduce a lot of complexity as well and forces us to either throw exceptions or use pointers in the case of null or empty geometries. This is extra complex when we deal with the fact that we have geometry collections:

For example lets use a `intersection` (with a polygon) visitor example -- I will attempt to reasonably show both sides here.

## Example with empty

```C++
template <typename T>
struct intersection_visitor {
   
   polygon<T> const& poly;

   intersection_visitor(polygon<T> const& poly_) : poly(poly_) {}

   geometry<T> operator() (empty const&) {
         return geometry<T>(); // empty default constructor
   }

   geometry<T> operator() (point<T> const& pt) {
         if (intersects(pt, poly)) {
             return geometry<T>(pt);  
         }
         return geometry<T>();
   }

   // Other geometry types here... multipoly, linestring, polygon, etc.

   geometry<T> operator() (geometry_collection<T> const& gc) {
        geometry_collection<T> new_gc;
        new_gc.reserve(gc.size());
        for (auto const& g : gc) {
              // use move operation instead of a copy here
              new_gc.push_back(apply_visitor(g, *this));
             // could also possibly be:
             /*
             auto new_g = apply_visitor(g, *this);
             if (!new_g.is<empty>()) {
                 new_gc.push_back(new_g);
             }
             */
        }
        return geometry<T>(new_gc);
   }

};
```

## Example with optional

```C++
template <typename T>
struct intersection_visitor {
   
   polygon<T> const& poly;

   intersection_visitor(polygon<T> const& poly_) : poly(poly_) {}

   optional_geometry<T> operator() (point<T> const& pt) {
         if (intersects(pt, poly)) {
             return optional_geometry<T>(pt);  
         }
         return optional_geometry<T>();
   }

   // Other geometry types here... multipoly, linestring, polygon, etc.

   optional_geometry<T> operator() (geometry_collection<T> const& gc) {
        geometry_collection<T> new_gc;
        new_gc.reserve(gc.size());
        for (auto const& g : gc) {
             auto new_optional_g = apply_visitor(g, *this);
             if (new_optional_g) {
                 new_gc.push_back(*new_optional_g);
             }
        }
        return optional_geometry<T>(new_gc);
   }

};
```

## Summary

Both of these sets of code are reasonably easy to program however, lets look at the interface that each of these would expose in the end.

```C++
template <typename T>
geometry<T> intersects(geometry<T> const& geom, polygon<T> const& poly);  
```

or

```
template <typename T>
optional_geometry<T> intersects(geometry<T> const& geom, polygon<T> const& poly);  
```

This means that more then likely the `optional_geometry` object is the **real** object we will be using when storing and managing the geometry objects. As we look how to write more algorithms around this, we will increasingly need to support methods and functions that work with this object. 

This concerns me in some ways, because suddenly we have a wrapper structure around our variant. Why do we need another layer? This extra structure seems like something we could be diving in and out of quickly if we chained operations, because we will need to operate on the variant quite a lot. Why not just have a null/empty case in the geometry object?

There are already cases where we can have `empty` or invalid data in our geometry object. For example, what does a `multi_point` or `line_string` mean with out any points? I don't feel like having a clear case of empty really adds much complexity.

**Comment by jfirebaugh** [comment]
> We will increasingly need to support methods and functions that work with this object.

For me, this is neither true nor desirable. I want to write as few methods and functions that need to deal with nullable geometries as possible. Don't you? It's much easier not to have to think about that additional case, decide upon a strategy for handling it, document the decision, and handle that ramifications of that decision everywhere downstream.

Where nullability _is_ actually an inevitable possibility, like in the intersection case, I want that called out very explicitly with a distinct and unusual type -- `optional<geometry>` -- so that I don't forget to account for it. Then I can dispose with that possibility as soon as possible, ideally in a single place, and go back to not having to be concerned or think about nullability.

But even if you do feel like you do need to write a lot of code that allows nullability -- then just write that code using `optional<geometry>`. As you've shown, it's not significantly more verbose or burdensome. But the advantage is that you can do so without issue, and I can continue to write code that _doesn't_ allow for nullability. With `optional<geometry>`, nullability is easy to opt in to, but nullability baked into the lowest-level definition is impossible to opt out of.

Regarding validity -- first off, I see validity as an orthogonal concern to nullability. An invalid geometry could be represented by a null geometry, but a null geometry can represent something else as well (e.g. no intersection), and conversely, an invalid geometry is not necessarily null. So they are two separate concepts, and shouldn't be conflated. I think it's still a great win if we can statically eliminate _some_ edge cases by disallowing nullability, even if there are other edge cases that stem from invalid geometry that we can't statically eliminate.

Secondly, if it were reasonably possible to statically enforce validity via the type system, I would absolutely want to do that as well. That would eliminate whole other swaths of possible bugs and programmer errors. Sadly, I don't think it is reasonably possible in the C++ type system. But where we can enforce constraints, as we can with nullability, I think we should do so.

**Comment by talaj** [comment]
What I found annoying about empty geometry in Mapnik is that empty geometry doesn't have the same interface as other geometry types. I mean `coordinate_type` in particular.

This will compile fine:

```c++
mapnik::geometry::line_string<double> geom;
mapnik::box2d<double> bbox = mapnik::geometry::envelope(geom);
```

But this will end up with `error: no type named ‘coordinate_type’ in ‘struct mapnik::geometry::geometry_empty’`:

```c++
mapnik::geometry::geometry_empty geom;
mapnik::box2d<double> bbox = mapnik::geometry::envelope(geom);
```

**Comment by springmeyer** [comment]
Per voice with @jfirebaugh and @flippmoke - this is now merged into the algorithms branch (not master). More review and discussion will be needed before a merge to master, since this would be a breaking change for users of the variant wrapping the geometry types (aka `mapbox::geometry::geometry_base`.

Echoing @flippmoke's comment in https://github.com/mapbox/geometry.hpp/pull/52#issuecomment-337988126, this `algorithms` branch will be a testbed @artemp and @flippmoke will use to refine the code as they actively work to ensure `geometry.hpp` will work seamlessly within https://github.com/mapbox/spatial-algorithms. Once that work is farther along, we'll circle back to resolve how to best enable geometry.hpp to balance the equally important needs of the spatial-algorithms and mbgl-native.

@talaj - Thanks for noticing that Mapnik compile issue. Please follow along with the work at https://github.com/mapbox/spatial-algorithms, which is where a design will emerge to avoid a compile error like that in the future (since spatial-algorithsm is standalone from mapnik and @artemp and @flippmoke are iterating on improved designs there).

Also, for users familiar with Mapnik (one of the main targets in the original design of geometry.hpp and the source of the original implementation inspiration - https://github.com/mapbox/geometry.hpp/issues/16), I want to clarify that Mapnik 3.1.x is now based on/working with geometry.hpp v0.9.x. However Mapnik does not yet use the `mapbox::geometry::geometry_base`. So, to my knowledge only Mapbox GL and deps at this point is using `mapbox::geometry::geometry_base`. Mapnik is currently using all the geometry types, but carrying its own `geometry_base` that stores an `geometry_empty` type: https://github.com/mapnik/mapnik/blob/f02a259011ec397f8152b0ad9b353483e80d5f96/include/mapnik/geometry.hpp#L49

**Pull request merged**
